name: nox
on:
    - push
jobs:
    run-nox:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Packages
              run: sudo apt install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config gir1.2-gtk-3.0 gir1.2-umockdev-1.0 libumockdev-dev umockdev
            - name: Running Tests
              uses: excitedleigh/setup-nox@v2.0.0
              run: nox
